kind: pipeline
type: docker
name: tests

steps:
  - name: tests
    image: tezedge/tezedge-ci-builder:nightly-2021-08-04-v9.5-tezos
    user: root
    commands:
      - cargo test

  - name: geiger-after
    image: tezedge/tezedge-ci-builder:nightly-2021-08-04-v9.5-tezos
    user: root
    commands:
      - cargo install cargo-geiger
      - cargo update
      - cargo geiger

  - name: geiger-before
    image: tezedge/tezedge-ci-builder:nightly-2021-08-04-v9.5-tezos
    user: root
    commands:
      - cargo install cargo-geiger
      - mkdir target && cd target && git clone https://github.com/tezedge/tezedge-actor-system --branch master
      - cd tezedge-actor-system
      - cargo update
      - cargo geiger
