hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
max_width = 100
comment_width = 80
wrap_comments = true 
unstable_features = true
merge_imports = true
match_arm_blocks = true
match_block_trailing_comma = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
format_code_in_doc_comments = true
format_strings = true
normalize_comments = false
where_single_line = true
skip_children = false
reorder_impl_items = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
edition = "2018"
version = "Two"
